# Generated by Django 5.0.2 on 2024-03-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0005_alter_message_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinchat',
            name='last_messages_update',
            field=models.DateTimeField(default=None),
        ),
    ]
