# Generated by Django 5.0.2 on 2024-03-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0007_alter_userinchat_last_messages_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='is_group_chat',
            field=models.BooleanField(default=True),
        ),
    ]
