# Generated by Django 5.0.2 on 2024-04-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0008_alter_chat_is_group_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='author',
            new_name='author_id',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='target',
            new_name='chat_id',
        ),
        migrations.AlterField(
            model_name='chat',
            name='creation_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userinchat',
            name='last_messages_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
