# Generated by Django 5.0.2 on 2024-04-14 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0009_rename_author_message_author_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='chat_id',
            new_name='chat',
        ),
    ]
