# Generated by Django 5.0.2 on 2024-04-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0010_rename_author_id_message_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinchat',
            name='join_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
