# Generated by Django 5.0.2 on 2024-04-20 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0011_alter_userinchat_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 4, 20, 13, 29, 13, 569936, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userinchat',
            name='last_messages_update',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 20, 16, 29, 13, 569693)),
        ),
    ]
