# Generated by Django 5.0.2 on 2024-04-20 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0013_alter_message_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinchat',
            name='last_messages_update',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 20, 16, 33, 27, 601548)),
        ),
    ]
