# Generated by Django 5.0.4 on 2024-05-01 22:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0018_alter_userinchat_last_messages_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinchat',
            name='last_messages_update',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 5, 1, 22, 10, 13, 264895)),
        ),
    ]
